import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Styles
import "@app/styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
  icons: [
    {
      url: "/icons/logo.svg",
    },
  ],
};

const MainLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={`${inter.variable}`}>{children}</body>
  </html>
);

export default MainLayout;
